/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false --config wrangler.production.jsonc` (hash: 9c42720b1de02eaca87f56c2eb571154)
interface __BaseEnv_Env {
  OAUTH_KV: KVNamespace;
  TOOL_OUTPUTS: KVNamespace;
  WORKSPACE_FILES: R2Bucket;
  DB: D1Database;
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  NANITES_CLOUDFLARE_SCRIPT_NAME: string;
  NANITES_SHOW_SETUP: string;
  ALLOW_TEST_AUTH: string;
  SENTRY_ENVIRONMENT: string;
  SENTRY_TRACES_SAMPLE_RATE: string;
  MANAGER_CONVERSATION_DISABLE_GITHUB_MCP: string;
  NANITES_LLM_BASE_URL: string;
  NANITES_LLM_FIXTURE: string;
  NANITES_AI_GATEWAY_ID: string;
  AUTH_COOKIE_SECRET: string;
  GITHUB_APP_PRIVATE_KEY: string;
  GITHUB_CLIENT_SECRET: string;
  GITHUB_WEBHOOK_SECRET: string;
  SigveloChatIngress: DurableObjectNamespace<import("./src/server").SigveloChatIngressV1>;
  SigveloManagerConversationAgent: DurableObjectNamespace<
    import("./src/server").SigveloManagerConversationAgentV1
  >;
  SigveloNaniteManager: DurableObjectNamespace<import("./src/server").SigveloNaniteManagerV1>;
  NanitesSetupAgent: DurableObjectNamespace<import("./src/server").NanitesSetupAgentV1>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "SigveloChatIngressV1"
      | "SigveloManagerConversationAgentV1"
      | "SigveloNaniteManagerV1"
      | "NanitesSetupAgentV1";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "NANITES_CLOUDFLARE_SCRIPT_NAME"
      | "NANITES_SHOW_SETUP"
      | "ALLOW_TEST_AUTH"
      | "SENTRY_ENVIRONMENT"
      | "SENTRY_TRACES_SAMPLE_RATE"
      | "MANAGER_CONVERSATION_DISABLE_GITHUB_MCP"
      | "NANITES_LLM_BASE_URL"
      | "NANITES_LLM_FIXTURE"
      | "NANITES_AI_GATEWAY_ID"
      | "AUTH_COOKIE_SECRET"
      | "GITHUB_APP_PRIVATE_KEY"
      | "GITHUB_CLIENT_SECRET"
      | "GITHUB_WEBHOOK_SECRET"
    >
  > {}
}
