/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 33ee64223f7220bf97aef427741275d3)
interface __BaseEnv_Env {
  OAUTH_KV: KVNamespace;
  TOOL_OUTPUTS: KVNamespace;
  WORKSPACE_FILES: R2Bucket;
  DB: D1Database;
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  NANITES_CLOUDFLARE_SCRIPT_NAME: "nanites-app-production";
  ALLOW_TEST_AUTH: "false";
  SENTRY_ENVIRONMENT: "production";
  SENTRY_TRACES_SAMPLE_RATE: "0.1";
  NANITES_LLM_BASE_URL: "";
  NANITES_LLM_FIXTURE: "";
  NANITES_SHOW_SETUP: string;
  AUTH_COOKIE_SECRET: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  GITHUB_APP_4046630_PRIVATE_KEY: string;
  GITHUB_APP_4046630_CLIENT_SECRET: string;
  GITHUB_APP_4046630_WEBHOOK_SECRET: string;
  SigveloChatIngress: DurableObjectNamespace<import("./src/server").SigveloChatIngress>;
  SigveloManagerConversationAgent: DurableObjectNamespace<
    import("./src/server").SigveloManagerConversationAgent
  >;
  SigveloNaniteManager: DurableObjectNamespace<import("./src/server").SigveloNaniteManager>;
  SigveloNaniteAgent: DurableObjectNamespace<import("./src/server").SigveloNaniteAgent>;
  NanitesSetupAgent: DurableObjectNamespace<import("./src/server").NanitesSetupAgent>;
  NANITE_RUN_WORKFLOW: Workflow<
    Parameters<import("./src/server").NaniteRunWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "SigveloChatIngress"
      | "SigveloManagerConversationAgent"
      | "SigveloNaniteManager"
      | "NanitesSetupAgent"
      | "SigveloNaniteAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "NANITES_CLOUDFLARE_SCRIPT_NAME"
      | "ALLOW_TEST_AUTH"
      | "SENTRY_ENVIRONMENT"
      | "SENTRY_TRACES_SAMPLE_RATE"
      | "NANITES_LLM_BASE_URL"
      | "NANITES_LLM_FIXTURE"
      | "NANITES_SHOW_SETUP"
      | "AUTH_COOKIE_SECRET"
      | "CLOUDFLARE_ACCOUNT_ID"
      | "R2_ACCESS_KEY_ID"
      | "R2_SECRET_ACCESS_KEY"
      | "GITHUB_APP_4046630_PRIVATE_KEY"
      | "GITHUB_APP_4046630_CLIENT_SECRET"
      | "GITHUB_APP_4046630_WEBHOOK_SECRET"
    >
  > {}
}
