/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=.env.example --include-runtime=false --strict-vars=false env.d.ts` (hash: d602fe64c16a499b793a3b1b0be0285a)
interface __BaseEnv_Env {
  OAUTH_KV: KVNamespace;
  WORKSPACE_FILES: R2Bucket;
  DB: D1Database;
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  SigveloManagerConversationAgent: DurableObjectNamespace<
    import("./src/server").SigveloManagerConversationAgent
  >;
  SigveloNaniteManager: DurableObjectNamespace<import("./src/server").SigveloNaniteManager>;
  SigveloNaniteAgent: DurableObjectNamespace<import("./src/server").SigveloNaniteAgent>;
  NanitesSetupAgent: DurableObjectNamespace<import("./src/server").NanitesSetupAgent>;
  NANITE_RUN_WORKFLOW: Workflow<
    Parameters<import("./src/server").NaniteRunWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "SigveloManagerConversationAgent"
      | "SigveloNaniteManager"
      | "NanitesSetupAgent"
      | "SigveloNaniteAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
