CREATE TABLE `account_installations` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_app_id` integer NOT NULL,
	`github_installation_id` integer NOT NULL,
	`status` text NOT NULL,
	`first_seen_at` integer NOT NULL,
	`last_seen_at` integer NOT NULL,
	`suspended_at` integer,
	`removed_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `account_installations_github_installation_id_unique` ON `account_installations` (`github_installation_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `account_installations_app_installation_unique` ON `account_installations` (`github_app_id`,`github_installation_id`);--> statement-breakpoint
CREATE TABLE `account_repositories` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_app_id` integer NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer NOT NULL,
	`github_repository` text NOT NULL,
	`first_seen_at` integer NOT NULL,
	`last_seen_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `account_repositories_account_repo_unique` ON `account_repositories` (`account_id`,`github_repository_id`);--> statement-breakpoint
CREATE TABLE `accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`github_account_id` integer NOT NULL,
	`github_account_login` text NOT NULL,
	`github_account_type` text NOT NULL,
	`github_account_avatar_url` text,
	`last_active_at` integer,
	`first_seen_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `accounts_github_account_id_unique` ON `accounts` (`github_account_id`);--> statement-breakpoint
CREATE TABLE `ai_usage_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_app_id` integer NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer,
	`nanite_id` text NOT NULL,
	`run_key` text NOT NULL,
	`request_id` text NOT NULL,
	`provider` text,
	`model` text NOT NULL,
	`session_affinity` text NOT NULL,
	`is_continuation` integer DEFAULT false NOT NULL,
	`step_count` integer DEFAULT 1 NOT NULL,
	`finish_reason` text,
	`ai_gateway_id` text NOT NULL,
	`ai_gateway_log_id` text NOT NULL,
	`actor_kind` text NOT NULL,
	`actor_github_user_id` integer,
	`actor_github_login` text,
	`actor_source` text NOT NULL,
	`cost_attributed_github_user_id` integer,
	`cost_attributed_github_login` text,
	`cost_attribution_basis` text,
	`started_at` integer NOT NULL,
	`completed_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ai_usage_facts_request_id_unique` ON `ai_usage_facts` (`request_id`);--> statement-breakpoint
CREATE TABLE `audit_events` (
	`id` text PRIMARY KEY NOT NULL,
	`occurred_at` integer NOT NULL,
	`event_name` text NOT NULL,
	`account_id` text NOT NULL,
	`github_app_id` integer NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer,
	`repository_full_name` text,
	`nanite_id` text NOT NULL,
	`run_key` text,
	`actor_kind` text NOT NULL,
	`actor_id` text,
	`actor_login` text,
	`actor_github_user_id` integer,
	`actor_github_login` text,
	`cost_attributed_github_user_id` integer,
	`cost_attributed_github_login` text,
	`cost_attribution_basis` text,
	`surface` text NOT NULL,
	`target_type` text NOT NULL,
	`target_id` text NOT NULL,
	`outcome` text NOT NULL,
	`reason_code` text,
	`request_id` text,
	`metadata_json` text DEFAULT '{}' NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `nanite_catalog` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_app_id` integer NOT NULL,
	`github_installation_id` integer NOT NULL,
	`nanite_id` text NOT NULL,
	`name` text NOT NULL,
	`enabled` integer NOT NULL,
	`event_source_type` text NOT NULL,
	`latest_version_id` text NOT NULL,
	`model_id` text DEFAULT '' NOT NULL,
	`repository_full_names_json` text DEFAULT '[]' NOT NULL,
	`repository_count` integer DEFAULT 0 NOT NULL,
	`trigger_event_count` integer DEFAULT 0 NOT NULL,
	`permission_count` integer DEFAULT 0 NOT NULL,
	`last_run_at` integer,
	`last_run_status` text,
	`created_by_github_user_id` integer,
	`created_by_github_login` text,
	`updated_by_github_user_id` integer,
	`updated_by_github_login` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `nanite_catalog_installation_nanite_unique` ON `nanite_catalog` (`github_installation_id`,`nanite_id`);--> statement-breakpoint
CREATE TABLE `nanite_run_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_app_id` integer NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer NOT NULL,
	`full_name` text NOT NULL,
	`run_key` text NOT NULL,
	`nanite_id` text NOT NULL,
	`trigger_kind` text NOT NULL,
	`trigger_pull_request_number` integer,
	`triggered_by_github_user_id` integer,
	`triggered_by_github_login` text,
	`actor_kind` text NOT NULL,
	`actor_github_user_id` integer,
	`actor_github_login` text,
	`actor_source` text NOT NULL,
	`cost_attributed_github_user_id` integer,
	`cost_attributed_github_login` text,
	`cost_attribution_basis` text,
	`status` text NOT NULL,
	`conclusion` text,
	`task` text NOT NULL,
	`summary` text,
	`output_url` text,
	`output_pull_request_number` integer,
	`output_pull_request_merged` integer,
	`output_pull_request_merged_at` integer,
	`output_additions` integer,
	`output_deletions` integer,
	`output_changed_files` integer,
	`model_runtime_path` text NOT NULL,
	`effective_model_id` text NOT NULL,
	`effective_gateway_id` text NOT NULL,
	`model_manifest_version_id` text NOT NULL,
	`model_resolved_at` integer NOT NULL,
	`implicit_failure_reason` text,
	`started_at` integer NOT NULL,
	`completed_at` integer,
	`last_updated_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `nanite_run_facts_installation_repo_run_unique` ON `nanite_run_facts` (`github_installation_id`,`github_repository_id`,`run_key`);
