CREATE TABLE `account_entitlements` (
	`account_id` text PRIMARY KEY NOT NULL,
	`plan_id` text DEFAULT 'internal' NOT NULL,
	`billing_provider` text,
	`external_billing_account_id` text,
	`seat_cap` integer,
	`repo_cap` integer,
	`run_cap` integer,
	`ai_token_allowance` integer,
	`browser_verification_allowance` integer,
	`ai_token_overage_count` integer DEFAULT 0 NOT NULL,
	`browser_verification_overage_count` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `account_installations` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_installation_id` integer NOT NULL,
	`status` text NOT NULL,
	`first_seen_at` integer NOT NULL,
	`last_seen_at` integer NOT NULL,
	`suspended_at` integer,
	`removed_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `account_installations_github_installation_id_unique` ON `account_installations` (`github_installation_id`);--> statement-breakpoint
CREATE TABLE `account_people` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_user_id` integer NOT NULL,
	`github_login` text NOT NULL,
	`relationship` text NOT NULL,
	`last_signed_in_at` integer,
	`last_active_at` integer,
	`first_seen_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `account_people_account_user_unique` ON `account_people` (`account_id`,`github_user_id`);--> statement-breakpoint
CREATE TABLE `account_repositories` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer NOT NULL,
	`github_repository` text NOT NULL,
	`first_seen_at` integer NOT NULL,
	`last_seen_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `account_repositories_account_repo_unique` ON `account_repositories` (`account_id`,`github_repository_id`);--> statement-breakpoint
CREATE TABLE `accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`github_account_id` integer NOT NULL,
	`github_account_login` text NOT NULL,
	`github_account_type` text NOT NULL,
	`github_account_avatar_url` text,
	`last_active_at` integer,
	`first_seen_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `accounts_github_account_id_unique` ON `accounts` (`github_account_id`);--> statement-breakpoint
CREATE TABLE `ai_usage_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer,
	`nanite_id` text,
	`run_key` text,
	`request_id` text NOT NULL,
	`provider` text,
	`model` text NOT NULL,
	`session_affinity` text,
	`is_continuation` integer DEFAULT false NOT NULL,
	`step_count` integer DEFAULT 1 NOT NULL,
	`finish_reason` text,
	`input_tokens` integer,
	`output_tokens` integer,
	`total_tokens` integer,
	`reasoning_tokens` integer,
	`cached_input_tokens` integer,
	`cache_write_tokens` integer,
	`raw_usage_json` text,
	`provider_metadata_json` text,
	`provider_billed_total_cost_usd_micros` integer,
	`ai_gateway_id` text,
	`ai_gateway_log_id` text,
	`ai_gateway_event_id` text,
	`actor_kind` text,
	`actor_github_user_id` integer,
	`actor_github_login` text,
	`actor_source` text,
	`billing_github_user_id` integer,
	`billing_github_login` text,
	`billing_attribution_basis` text,
	`estimated_input_cost_usd_micros` integer,
	`estimated_output_cost_usd_micros` integer,
	`estimated_total_cost_usd_micros` integer,
	`started_at` integer NOT NULL,
	`completed_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ai_usage_facts_request_id_unique` ON `ai_usage_facts` (`request_id`);--> statement-breakpoint
CREATE TABLE `audit_events` (
	`id` text PRIMARY KEY NOT NULL,
	`occurred_at` integer NOT NULL,
	`event_name` text NOT NULL,
	`account_id` text,
	`github_installation_id` integer,
	`github_repository_id` integer,
	`repository_full_name` text,
	`nanite_id` text,
	`run_key` text,
	`actor_kind` text NOT NULL,
	`actor_id` text,
	`actor_login` text,
	`actor_github_user_id` integer,
	`actor_github_login` text,
	`billing_github_user_id` integer,
	`billing_github_login` text,
	`billing_basis` text,
	`surface` text NOT NULL,
	`target_type` text NOT NULL,
	`target_id` text,
	`outcome` text NOT NULL,
	`reason_code` text,
	`request_id` text,
	`metadata_json` text DEFAULT '{}' NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `auth_funnel_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text,
	`github_installation_id` integer,
	`github_repository_id` integer,
	`github_user_id` integer,
	`github_login` text,
	`event_type` text NOT NULL,
	`metadata_json` text DEFAULT '{}' NOT NULL,
	`occurred_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `deployment_github_app_config` (
	`id` text PRIMARY KEY NOT NULL,
	`app_id` integer NOT NULL,
	`slug` text NOT NULL,
	`html_url` text NOT NULL,
	`owner_login` text,
	`owner_type` text,
	`selected_github_installation_id` integer,
	`client_id` text NOT NULL,
	`client_secret_binding` text NOT NULL,
	`webhook_secret_binding` text NOT NULL,
	`private_key_binding` text NOT NULL,
	`permissions_json` text NOT NULL,
	`events_json` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `nanite_catalog` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text,
	`github_installation_id` integer NOT NULL,
	`nanite_id` text NOT NULL,
	`name` text NOT NULL,
	`enabled` integer NOT NULL,
	`event_source_type` text NOT NULL,
	`latest_version_id` text NOT NULL,
	`model_id` text DEFAULT '' NOT NULL,
	`repository_full_names_json` text DEFAULT '[]' NOT NULL,
	`repository_count` integer DEFAULT 0 NOT NULL,
	`trigger_event_count` integer DEFAULT 0 NOT NULL,
	`permission_count` integer DEFAULT 0 NOT NULL,
	`last_run_at` integer,
	`last_run_status` text,
	`created_by_github_user_id` integer,
	`created_by_github_login` text,
	`updated_by_github_user_id` integer,
	`updated_by_github_login` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `nanite_catalog_installation_nanite_unique` ON `nanite_catalog` (`github_installation_id`,`nanite_id`);--> statement-breakpoint
CREATE TABLE `nanite_run_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`github_installation_id` integer NOT NULL,
	`github_repository_id` integer NOT NULL,
	`full_name` text NOT NULL,
	`run_key` text NOT NULL,
	`nanite_id` text NOT NULL,
	`variant` text NOT NULL,
	`trigger_kind` text NOT NULL,
	`trigger_pull_request_number` integer,
	`triggered_by_github_user_id` integer,
	`triggered_by_github_login` text,
	`actor_kind` text,
	`actor_github_user_id` integer,
	`actor_github_login` text,
	`actor_source` text,
	`billing_github_user_id` integer,
	`billing_github_login` text,
	`billing_attribution_basis` text,
	`status` text NOT NULL,
	`conclusion` text,
	`phase` text NOT NULL,
	`task` text NOT NULL,
	`summary` text,
	`output_url` text,
	`output_pull_request_number` integer,
	`output_pull_request_merged` integer,
	`output_pull_request_merged_at` integer,
	`output_additions` integer,
	`output_deletions` integer,
	`output_changed_files` integer,
	`model_runtime_path` text,
	`effective_model_id` text,
	`effective_gateway_id` text,
	`model_manifest_version_id` text,
	`model_resolved_at` integer,
	`config_source` text,
	`implicit_failure_reason` text,
	`missing_exit_tool_reminder_count` integer DEFAULT 0 NOT NULL,
	`total_message_count` integer DEFAULT 0 NOT NULL,
	`runtime_activity_part_count` integer DEFAULT 0 NOT NULL,
	`reasoning_block_count` integer DEFAULT 0 NOT NULL,
	`tool_invocation_count` integer DEFAULT 0 NOT NULL,
	`tool_failure_count` integer DEFAULT 0 NOT NULL,
	`model_turn_count` integer DEFAULT 0 NOT NULL,
	`continuation_turn_count` integer DEFAULT 0 NOT NULL,
	`workspace_file_count` integer,
	`workspace_directory_count` integer,
	`workspace_total_bytes` integer,
	`workspace_hydration_duration_ms` integer,
	`workspace_hydration_heartbeat_count` integer,
	`started_at` integer NOT NULL,
	`completed_at` integer,
	`last_updated_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `nanite_run_facts_installation_repo_run_unique` ON `nanite_run_facts` (`github_installation_id`,`github_repository_id`,`run_key`);--> statement-breakpoint
CREATE TABLE `platform_usage_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text,
	`github_installation_id` integer,
	`github_repository_id` integer,
	`run_key` text,
	`category` text NOT NULL,
	`event_key` text NOT NULL,
	`status` text,
	`quantity` integer DEFAULT 1 NOT NULL,
	`duration_ms` integer,
	`metadata_json` text DEFAULT '{}' NOT NULL,
	`occurred_at` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`github_installation_id`) REFERENCES `account_installations`(`github_installation_id`) ON UPDATE no action ON DELETE cascade
);
