/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as McpAuthorizeRouteImport } from "./routes/mcp-authorize";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedNanitesRouteRouteImport } from "./routes/_authenticated/nanites/route";

const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: "/mcp-authorize",
  path: "/mcp-authorize",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedNanitesRouteRoute =
  AuthenticatedNanitesRouteRouteImport.update({
    id: "/nanites",
    path: "/nanites",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/mcp-authorize": typeof McpAuthorizeRoute;
  "/nanites": typeof AuthenticatedNanitesRouteRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/mcp-authorize": typeof McpAuthorizeRoute;
  "/nanites": typeof AuthenticatedNanitesRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/mcp-authorize": typeof McpAuthorizeRoute;
  "/_authenticated/nanites": typeof AuthenticatedNanitesRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/mcp-authorize" | "/nanites";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/mcp-authorize" | "/nanites";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/mcp-authorize"
    | "/_authenticated/nanites";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  McpAuthorizeRoute: typeof McpAuthorizeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/mcp-authorize": {
      id: "/mcp-authorize";
      path: "/mcp-authorize";
      fullPath: "/mcp-authorize";
      preLoaderRoute: typeof McpAuthorizeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/nanites": {
      id: "/_authenticated/nanites";
      path: "/nanites";
      fullPath: "/nanites";
      preLoaderRoute: typeof AuthenticatedNanitesRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNanitesRouteRoute: typeof AuthenticatedNanitesRouteRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNanitesRouteRoute: AuthenticatedNanitesRouteRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  McpAuthorizeRoute: McpAuthorizeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
