/**
 * Dotted event names stay stable as the app grows from JSON logs today to more
 * complete tracing and dashboards later.
 */
export const LOG_EVENTS = {
  AGENT_EVENT_ERROR: "agent.event.error",
  AGENT_EVENT_OBSERVED: "agent.event.observed",
  AGENT_SCHEDULE_EXECUTED: "agent.schedule.executed",
  AGENT_WEBSOCKET_ERROR: "agent.websocket.error",
  API_REQUEST_FAILED: "api.request.failed",
  API_REQUEST_COMPLETED: "api.request.completed",
  API_REQUEST_NOT_FOUND: "api.request.not_found",
  API_UNHANDLED_ERROR: "api.request.unhandled",
  GITHUB_API_REQUEST_FAILED: "github.api.request.failed",
  GITHUB_API_REQUEST_SUCCEEDED: "github.api.request.succeeded",
  GITHUB_WEBHOOK_RECEIVED: "github.webhook.received",
  MCP_SERVER_ADD_FAILED: "mcp.server.add.failed",
  MCP_SERVER_REMOVE_FAILED: "mcp.server.remove.failed",
  NANITE_AGENT_RUN_ACCEPTED: "nanite.agent.run.accepted",
  NANITE_AGENT_RUN_SUBMITTED: "nanite.agent.run.submitted",
  NANITE_CHAT_ERROR: "nanite.chat.error",
  NANITE_CHAT_RESPONSE: "nanite.chat.response",
  NANITE_DEPROVISIONED: "nanite.deprovisioned",
  NANITE_MANAGER_MAINTENANCE_COMPLETED: "nanite.manager.maintenance.completed",
  NANITE_RUN_COMPLETED: "nanite.run.completed",
  NANITE_RUN_CREATED: "nanite.run.created",
  NANITE_RUN_DEDUPED: "nanite.run.deduped",
  NANITE_RUN_DISPATCH_FAILED: "nanite.run.dispatch.failed",
  NANITE_RUN_DISPATCH_STARTED: "nanite.run.dispatch.started",
  NANITE_RUN_DISPATCH_SUCCEEDED: "nanite.run.dispatch.succeeded",
  NANITE_RUNTIME_ACTIVITY_RECORDED: "nanite.runtime_activity.recorded",
  NANITE_SUBMISSION_STATUS: "nanite.submission.status",
  NANITE_TOOL_CALL_FINISHED: "nanite.tool_call.finished",
  NANITE_TOOL_OUTPUT_TRUNCATED: "nanite.tool_output.truncated",
  NANITE_TRIGGER_EVALUATED: "nanite.trigger.evaluated",
  NANITE_TURN_STARTED: "nanite.turn.started",
  NANITE_STEP_FINISHED: "nanite.step.finished",
  NANITE_WORKSPACE_HYDRATION_COMPLETED: "nanite.workspace.hydration.completed",
  NANITE_WORKSPACE_HYDRATION_FAILED: "nanite.workspace.hydration.failed",
  NANITE_WORKSPACE_HYDRATION_REF_FALLBACK: "nanite.workspace.hydration.ref_fallback",
  NANITE_WORKSPACE_HYDRATION_REF_RETRY: "nanite.workspace.hydration.ref_retry",
  NANITE_WORKSPACE_HYDRATION_HEARTBEAT: "nanite.workspace.hydration.heartbeat",
  NANITE_WORKSPACE_HYDRATION_STARTED: "nanite.workspace.hydration.started",
} as const satisfies Record<string, string>;
