/**
 * Shared OpenTelemetry-style attribute keys for structured logs.
 *
 * Use standard OTEL semantic keys where they fit. Use `sigvelo.*` when the
 * domain concept is application-specific and has no good standard attribute.
 */
export const OTEL_ATTRS = {
  HTTP_REQUEST_METHOD: "http.request.method",
  HTTP_RESPONSE_STATUS_CODE: "http.response.status_code",
  HTTP_RESPONSE_STATUS_CLASS: "http.response.status_class",
  HTTP_ROUTE: "http.route",
  URL_FULL: "url.full",
  URL_PATH: "url.path",
  ERROR_TYPE: "error.type",
  EXCEPTION_MESSAGE: "exception.message",
  RPC_SYSTEM: "rpc.system",
  RPC_METHOD: "rpc.method",
  GITHUB_INSTALLATION_ID: "github.installation.id",
  GITHUB_OPERATION: "github.operation",
  GITHUB_REPOSITORY_FULL_NAME: "github.repository.full_name",
  GITHUB_WEBHOOK_DELIVERY_ID: "github.webhook.delivery_id",
  GITHUB_WEBHOOK_EVENT_NAME: "github.webhook.event_name",
  GITHUB_WEBHOOK_EVENT_ACTION: "github.webhook.event_action",
  GIT_BRANCH_NAME: "git.branch.name",
  REQUEST_ID: "sigvelo.request.id",
  REQUEST_DURATION_MS: "sigvelo.request.duration_ms",
  ROUTE_TARGET: "sigvelo.route.target",
  AGENT_CLASS: "sigvelo.agent.class",
  AGENT_NAME: "sigvelo.agent.name",
  AGENT_EVENT_TYPE: "sigvelo.agent.event.type",
  AGENT_EVENT_TIMESTAMP: "sigvelo.agent.event.timestamp",
  MCP_SERVER_ID: "sigvelo.mcp.server.id",
  MCP_SERVER_NAME: "sigvelo.mcp.server.name",
  NANITE_PHASE: "sigvelo.nanite.phase",
  NANITE_ACTIVITY_STATE: "sigvelo.nanite.activity.state",
  NANITE_ID: "sigvelo.nanite.id",
  NANITE_MANAGER_NAME: "sigvelo.nanite.manager.name",
  NANITE_RUN_ID: "sigvelo.nanite.run.id",
  NANITE_RUN_KEY: "sigvelo.nanite.run.key",
  NANITE_RUN_STATUS: "sigvelo.nanite.run.status",
  NANITE_SUBMISSION_ID: "sigvelo.nanite.submission.id",
  NANITE_TOOL_NAME: "sigvelo.nanite.tool.name",
  NANITE_TOOL_OUTPUT_ARTIFACT_ID: "sigvelo.nanite.tool_output.artifact_id",
  NANITE_TOOL_OUTPUT_ORIGINAL_CHARS: "sigvelo.nanite.tool_output.original_chars",
  NANITE_TOOL_OUTPUT_RETURNED_CHARS: "sigvelo.nanite.tool_output.returned_chars",
  NANITE_TRIGGER_ACCEPTED: "sigvelo.nanite.trigger.accepted",
  NANITE_TRIGGER_EVENT: "sigvelo.nanite.trigger.event",
  NANITE_TRIGGER_INTENT_COUNT: "sigvelo.nanite.trigger.intent_count",
  NANITE_TRIGGER_TYPE: "sigvelo.nanite.trigger.type",
  NANITE_WORKSPACE_HYDRATION_ELAPSED_MS: "sigvelo.nanite.workspace.hydration.elapsed_ms",
  NANITE_WORKSPACE_HYDRATION_HEARTBEAT_COUNT: "sigvelo.nanite.workspace.hydration.heartbeat_count",
  PROCESS_RUNTIME_NAME: "process.runtime.name",
} as const satisfies Record<string, string>;
